### PR TITLE
Setup translation infrastructure

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by ofedoren** [comment]
Updated .gemspec to actually include the locale files.

**Comment by ofedoren** [comment]
Packit fails the only fails I'm glad to observe :) indication that we finally will have translations :facepalm: after we update rpmspec.

**Review by ekohl — APPROVED** [review]

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**

**Comment by stejskalleos** [comment]
Thanks @ofedoren @ekohl

**Pull request merged**
