### PR TITLE
Add test support

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by adamruzicka** [comment]
While this looks fine, the tests don't seem to be actually running https://github.com/ofedoren/hammer-cli-foreman-ansible/runs/5739825298?check_suite_focus=true ? Or are they just quiet?

**Comment by ofedoren** [comment]
> While this looks fine, the tests don't seem to be actually running https://github.com/ofedoren/hammer-cli-foreman-ansible/runs/5739825298?check_suite_focus=true ? Or are they just quiet?

There are just no tests for the moment :) First tests to run are being added here https://github.com/theforeman/hammer-cli-foreman-ansible/pull/10

**Review by adamruzicka — APPROVED** [review]
Oh, right. Let's get this in then

**Comment by adamruzicka** [comment]
Thank you @ofedoren !

**Pull request merged**
